language: php
sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true
    include:
        - php: 7.4
          env: SKELETON_VERSION="^3.4"
        - php: 7.4
          env: SKELETON_VERSION="^4.4"
        - php: 7.4
          env: SKELETON_VERSION="^5.0"

before_install:
    - phpenv config-rm xdebug.ini || true
    - export SYMFONY_ENDPOINT=https://flex.symfony.com/r/github.com/symfony/recipes-contrib/${TRAVIS_PULL_REQUEST}
    - export PACKAGES=$(curl -s $SYMFONY_ENDPOINT | sed -En 's/.*composer req "([^"]+)".*/\1/p')
    - echo "$PACKAGES"

install:
    - composer create-project "symfony/skeleton:${SKELETON_VERSION}" flex
    - cd flex
    - composer config extra.symfony.allow-contrib true

script:
    - |
      EXIT_CODE=$(composer req --ignore-platform-reqs $(echo $PACKAGES));
      echo "Exit code: $EXIT_CODE";
      if [[ EXIT_CODE -eq 0 ]]; then
        exit 0;
      elif [[ EXIT_CODE -eq 1 ]]; then
        echo "Could not install package";
        exit 1;
      elif [[ EXIT_CODE -eq 2 ]]; then
        echo "Could not resolve dependencies. You can ignore this error if your package does not support Symfony $SKELETON_VERSION";
        exit 1;
      fi

      exit $EXIT_CODE;

