# Configuration file for the MaksZeTelemetry bundle
#
# For more information about the bundle settings visit:
# https://github.com/maksze/MaksZeTelemetryBundle/blob/master/README.md

maksze_telemetry:
    yandex_metrika:
        #- {id: any_id}
    yandex_webmaster:
        #- {id: any_id}
    google_search_console:
        #- {id: any_id}
    google_analytics:
        #- {id: any_id}
