netopia_mobilpay_return_url:
    controller: "@NetopiaMobilPayBundle/Controller/NetopiaMobilpayController.php::returnUrlAction"
    path: /netopia-mobilpay/thank-you
    methods: GET

netopia_mobilpay_confirm_url:
    controller: "@NetopiaMobilPayBundle/Controller/NetopiaMobilpayController.php::confirmUrlAction"
    path: /netopia-mobilpay/confirm
    methods: POST
