# Read more about client options at: https://github.com/kriswallsmith/Buzz/blob/master/doc/client.md
services:
    _defaults:
        public: false

    # Tell the auto wire system to use "FileGetContents" client as default client.
    # Set this to any of the other clients below (e.g. Curl or MultiCurl) to use a different default client.
    Buzz\Client\BuzzClientInterface: '@Buzz\Client\FileGetContents'

    # Clients
    Buzz\Client\Curl:
        arguments:
            - timeout: 10

    Buzz\Client\FileGetContents:
        arguments:
            - timeout: 10

    Buzz\Client\MultiCurl:
        arguments:
            - timeout: 10

    # Browser
    Buzz\Browser:
        arguments: ['@Buzz\Client\BuzzClientInterface']
        calls:
            - ['addMiddleware', ['@Buzz\Middleware\ContentLengthMiddleware']]
            - ['addMiddleware', ['@Buzz\Middleware\LoggerMiddleware']]

    # Middlewares
    Buzz\Middleware\ContentLengthMiddleware: ~

    Buzz\Middleware\LoggerMiddleware:
        arguments: ['@?logger']
        tags:
            - { name: monolog.logger, channel: buzz }
