amqp_handler:
    connection: 'tcp://guest:guest@172.18.0.01:5672'
    queues_properties:
        sync_queue:
            name: stores_sync
            message_ttl: 10000 # 10 seconds
        async_queue:
            name: stores_async
            message_ttl: 10000 # 10 seconds
