#parameters:
#  disjfa_mozaic.unsplash.application_id: ''
#  disjfa_mozaic.unsplash.secret: ''

disjfa_mozaic:
  unsplash:
    application_id: '%env(resolve:UNSPLASH_APPLICATION_ID)%'
    secret: '%env(resolve:UNSPLASH_APPLICATION_SECRET)%'
