# See full config at https://github.com/backup-manager/symfony
bm_backup_manager:
    database:
        development:
            dsn: '%env(mysql://db_user:db_password@127.0.0.1:3306/db_name)%'
    storage:
        local:
            type: Local
            root: "%kernel.cache_dir%/db"
