jmose_command_scheduler:

    # Default directory where scheduler will write output files
    #  This default value assume that php bin/console is launched from project's root and that the directory is writable
    # if log_path is set to false, logging to files is disabled at all
    log_path: "%kernel.logs_dir%"

    # This default value disables timeout checking (see monitoring), set to a numeric value (seconds) to enable it
    lock_timeout: false

    # receivers for reporting mails
    monitor_mail: []

    # set a custom subject for monitor mails (first placeholder will be replaced by the hostname, second by the date)
    monitor_mail_subject: cronjob monitoring %s, %s

    # to send "everything's all right" emails to receivers for reporting mails set this value to "true" (see monitoring)
    send_ok: false

    # Namespaces listed here won't be listed in the list
    excluded_command_namespaces:
        - _global
        - scheduler
        - server
        - container
        - config
        - generate
        - init
        - router
        - doctrine
        - debug

    # Doctrine manager
    doctrine_manager: default
