parameters:
    # Adds a fallback NEO4J_DEFAULT_CONNECTION_DSN if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(NEO4J_DEFAULT_CONNECTION_DSN): ''

neo4j:
    connections:
        default:
            dsn: '%env(resolve:NEO4J_DEFAULT_CONNECTION_DSN)%'
