oka_pagination:
    db_driver: orm
    model_manager_name: ~
    item_per_page: 10
    max_page_number: 400
    template: 'OkaPaginationBundle:Pagination:paginate.html.twig'
    request:
        query_map:
            page: page
            item_per_page: item_per_page
            sort: sort
            desc: desc
            distinct: distinct
            fields: fields
        sort:
            delimiter: ','
    twig:
        enable_extension: false
