services:
    _defaults:
        autowire: true

    Prooph\EventStoreBusBridge\EventPublisher:
        tags:
            - { name: 'prooph_event_store.app.plugin' }

    # Uncomment these lines if your event store support transaction
    # Read more: http://docs.getprooph.org/event-store/implementations/pdo_event_store/variants.html#3-2-1-2
    #
    # Prooph\EventStore\TransactionalEventStore: '@Prooph\EventStore\EventStore'
    #
    # Prooph\EventStoreBusBridge\TransactionManager:
    #     tags:
    #         - { name: 'prooph_service_bus.app_command_bus.plugin' }
