docusign:
    access_token: "YourAccessToken"
    account_id: "yourAccountId"
    default_signer_name: "Your Signer Name"
    default_signer_email: "you@email.tld"
    signatures:
        default_document_type:
            signatures:
                -
                    page: 1 # default
                    x_position: 200 # top left corner in pixels
                    y_position: 400 # top left corner in pixels
    storages:
        docusign.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/default'
