prooph_event_store:
    stores:
        default:
            event_store: 'app.event_store.default'
            # repositories:
            #     App\EventSourcing\TodoRepository:
            #         aggregate_type: App\EventSourcing\Todo
            #         aggregate_translator: Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator

services:
    _defaults:
        public: false

    Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator: ~
