picoss_yousign:
    env: '%env(YOUSIGN_ENV)%'
    api_key: '%env(YOUSIGN_API_KEY)%'
    username: '%env(YOUSIGN_USERNAME)%'
    password: '%env(YOUSIGN_PASSWORD)%'
#    soap_options:
#        tarce: 1
