oneup_flysystem:
    adapters:
        my_adapter:
            local:
                directory: "%kernel.root_dir%/cache"

    filesystems:
        my_filesystem:
            adapter: my_adapter
            # optional - defines the default visibility of the filesystem: `public` or `private`(default)
            visibility: private

