oneup_flysystem:
    adapters:
        default_adapter:
            local:
                directory: "%kernel.root_dir%/var/cache"

    filesystems:
        default_filesystem:
            adapter: default_adapter
