sulu_form:
    mail:
        from: "%env(resolve:SULU_FORM_EMAIL_FROM)%"
        to: "%env(resolve:SULU_FORM_EMAIL_TO)%"
        sender: "%env(resolve:SULU_FORM_EMAIL_SENDER)%"

framework:
    esi: true
    fragments: true
