#
# All configuration options are described here:
# https://github.com/meritoo/common-bundle/blob/master/docs/Configuration.md
#
meritoo_common:
    form:
        novalidate: "%env(resolve:MERITOO_FORM_NOVALIDATE)%"
