sb_kafka:
    producers:
        configuration:
            group_id: 'main_group'
            log_connection_close: 'false'
            metadata_broker_list: '%env(KAFKA_BROKERS)%'
            queue_buffering_max_messages: 10000000

    consumers:
        configuration:
            group_id: 'main_group'
            log_connection_close: 'false'
            metadata_broker_list: '%env(KAFKA_BROKERS)%'

    topics:
        configuration:
            auto_offset_reset: smallest
